version: "2"
name: terragrunt
canonical: terragrunt
author: Sivasubramanian Veerabahu
status: private
description: terragrunt
image: ""
keywords:
- terragrunt
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
